vehicle_controller: # Name of node
  ros__parameters: # ROS parameters
    vmax: 10
    # WP: [latitude, longitude, relative altitude]
    gps_WP1: [37.464689, 126.952328, 5.0]
    gps_WP2: [37.463140, 126.950369, 5.0]
