vehicle_controller: # Name of node
  ros__parameters: # ROS parameters
    logging: True
    vmax: 5
    # WP: [latitude, longitude, relative altitude]
    gps_WP1: [37.464631, 126.949872, 5.0]
    gps_WP2: [37.464841, 126.950271, 5.0]
