vehicle_controller: # Name of node
  ros__parameters: # ROS parameters
    vmax: 5.0
    # WP: [latitude, longitude, relative altitude]
    # 37.465194. 126.950070
    gps_WP1: [37.465129, 126.950059, 5.0]
    gps_WP2: [37.464532, 126.950008, 4.0]
    
