vehicle_controller: # Name of node
  ros__parameters: # ROS parameters
    vmax: 10
    # WP: [latitude, longitude, relative altitude]
    gps_WP1: [37.4647855, 126.9500355, 15.0]
    gps_WP2: [37.46478549999134, 126.9500807146237, 5.0]
